apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: ci
  labels:
    pv: mysql-pv
spec:
  claimRef:
    name: mysql-pvc
    namespace: ci
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /mnt/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: ci
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      pv: mysql-pv