server:
  port: 9090

spring:
  application:
    name: "api-builder"
  datasource:
    url: "jdbc:mysql://localhost:3307/beans"
    username: beans
    password: beans
    driver-class-name: com.mysql.cj.jdbc.Driver
com:
  opentrends:
    api-builder:
      providers:
        jenkins:
          url: jenkins
          job: jenkins
          user: jenkins
          pass: jenkins

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

logging:
  file:
    path: "/api-builder/logs"
    max-size: "10MB"
    max-history: "10"
    total-size-cap: "1GB"
  default-pattern: "[%thread][%logger][%date{ISO8601,Europe/Madrid}][%level][%class][%msg]%n"
  pattern:
    file: "${logging.default-pattern}"
    console: "${logging.default-pattern}"