server:
  port: 9090

spring:
  application:
    name: "api-builder"
  datasource:
    url: "jdbc:mysql://${DB_HOST}/${DB}"
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
com:
  opentrends:
    api-builder:
      providers:
        jenkins:
          url: ${JENKINS_HOST}
          job: ${CI_JOB}
          user: ${JENKINS_USER}
          pass: ${JENKINS_PASS}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

logging:
  file:
    name: "api-builder"
    path: "/api-builder/logs"
    max-size: "10MB"
    max-history: "10"
    total-size-cap: "1GB"
  default-pattern: "[%thread][%logger][%date{ISO8601,Europe/Madrid}][%level][%class][%msg]%n"
  pattern:
    file: "${logging.default-pattern}"
    console: "${logging.default-pattern}"